// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACyYBlG_JRmkX5aEzG1BQifQx83rFzXjQ',
    appId: '1:727123691804:web:a55dbe5b4bcd1030c692d9',
    messagingSenderId: '727123691804',
    projectId: 'fir-practice-df9c2',
    authDomain: 'fir-practice-df9c2.firebaseapp.com',
    storageBucket: 'fir-practice-df9c2.appspot.com',
    measurementId: 'G-7GWKC4H9JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhANGuuQbv9DH_l5ySIB09ypD467P5aEI',
    appId: '1:727123691804:android:2c4cd0b2773b98c2c692d9',
    messagingSenderId: '727123691804',
    projectId: 'fir-practice-df9c2',
    storageBucket: 'fir-practice-df9c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUPBHGqOPwOsShFbM6iYaQpXJL6RXYRk',
    appId: '1:727123691804:ios:f8e086ca5a3bd6e8c692d9',
    messagingSenderId: '727123691804',
    projectId: 'fir-practice-df9c2',
    storageBucket: 'fir-practice-df9c2.appspot.com',
    iosClientId: '727123691804-7l65587cp2msmp64f6isrr4ajskoljtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUPBHGqOPwOsShFbM6iYaQpXJL6RXYRk',
    appId: '1:727123691804:ios:ea3e1213a298088dc692d9',
    messagingSenderId: '727123691804',
    projectId: 'fir-practice-df9c2',
    storageBucket: 'fir-practice-df9c2.appspot.com',
    iosClientId: '727123691804-8jnlh9jtfpmmqec1qqsl6unihgqsqg0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
